#!/usr/bin/env bash

revert() {
  swaymsg "output * dpms on"
}
trap revert SIGHUP SIGINT SIGTERM # How to fix this line?
swaymsg "output * dpms off"
swaylock -k -e -f -i  ~/.config/sway/background-redhat-1920x1200-lock.png
revert

